import 'package:flair_pair/packages.dart';

class PairingRepository {
  final Map<String, List<PairingModel>> _allPairings = {
    'Wine': [
      PairingModel(
        foodName: 'Chicken Alfredo',
        alcoholName: 'Pinot Grigio',
        pairingDescription: 'Pair the creamy richness of Chicken Alfredo with a crisp Pinot Grigio.',
        keyIngredients: ['Chicken breast', 'Fettuccine pasta', 'Alfredo sauce', 'Parmesan cheese'],
        flavorProfile: 'Creamy and indulgent',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Eggplant Parmesan',
        alcoholName: 'Merlot',
        pairingDescription: 'Savor the layers of Eggplant Parmesan with the velvety notes of Merlot wine.',
        keyIngredients: ['Eggplant', 'Marinara sauce', 'Mozzarella cheese', 'Breadcrumbs'],
        flavorProfile: 'Savory and comforting',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Cheese',
        alcoholName: 'Wine',
        pairingDescription: 'A classic combination for wine enthusiasts.',
        keyIngredients: ['Cheese', 'Wine'],
        flavorProfile: 'Classic',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Chocolate',
        alcoholName: 'Wine',
        pairingDescription: 'Indulge in the sweet harmony of chocolate and wine.',
        keyIngredients: ['Chocolate', 'Wine'],
        flavorProfile: 'Sweet',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Grilled Vegetables',
        alcoholName: 'White Wine',
        pairingDescription: 'Lighten up with grilled veggies and a crisp white wine.',
        keyIngredients: ['Grilled Vegetables', 'White Wine'],
        flavorProfile: 'Fresh',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Cheese Plate',
        alcoholName: 'Red Wine',
        pairingDescription: 'A classic combination for wine enthusiasts.',
        keyIngredients: ['Cheese', 'Crackers', 'Grapes'],
        flavorProfile: 'Rich and Fruity',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Dark Chocolate',
        alcoholName: 'Port',
        pairingDescription: 'Indulge in the sweet harmony of chocolate and wine.',
        keyIngredients: ['Dark Chocolate'],
        flavorProfile: 'Sweet and Decadent',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Grilled Salmon',
        alcoholName: 'Chardonnay',
        pairingDescription: 'Lighten up with grilled salmon and a buttery Chardonnay.',
        keyIngredients: ['Salmon', 'Lemon', 'Herbs'],
        flavorProfile: 'Buttery and Citrusy',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Oysters',
        alcoholName: 'Chardonnay',
        pairingDescription: 'Savor the briny goodness of oysters with a buttery Chardonnay.',
        keyIngredients: ['Oysters', 'Chardonnay'],
        flavorProfile: 'Buttery',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Mushroom Risotto',
        alcoholName: 'Red Wine',
        pairingDescription: 'Savor the rich and earthy flavors of mushroom risotto with a glass of red wine.',
        keyIngredients: ['Arborio rice', 'Mushrooms', 'Parmesan cheese', 'Vegetable broth'],
        flavorProfile: 'Savory and hearty',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Caprese Salad',
        alcoholName: 'Rosé',
        pairingDescription: 'Enjoy the freshness of a Caprese salad with the light and fruity notes of rosé wine.',
        keyIngredients: ['Tomatoes', 'Fresh mozzarella', 'Basil', 'Balsamic glaze'],
        flavorProfile: 'Fresh and vibrant',
        vegan: true,
        glutenFree: true,
      ),
    ],  // end of wine key (11 pairings)
    'Beer': [
      PairingModel(
        foodName: 'Pizza',
        alcoholName: 'Beer',
        pairingDescription: 'An all-time favorite pairing for a casual meal.',
        keyIngredients: ['Pizza', 'Beer'],
        flavorProfile: 'Comforting',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Pretzels',
        alcoholName: 'Beer',
        pairingDescription: 'Pretzels go well with a cold beer.',
        keyIngredients: ['Pretzels', 'Beer'],
        flavorProfile: 'Salty',
        vegan: true,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Burger and Fries',
        alcoholName: 'IPA',
        pairingDescription: 'A classic pairing for beer lovers.',
        keyIngredients: ['Beef Patty', 'Brioche Bun', 'Potato Fries'],
        flavorProfile: 'Hoppy and Savory',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Fish Tacos',
        alcoholName: 'Wheat Beer',
        pairingDescription: 'Light and refreshing pairing for a summer day.',
        keyIngredients: ['Fish Fillets', 'Tortillas', 'Cabbage Slaw'],
        flavorProfile: 'Crisp and Citrusy',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Pretzel Bites',
        alcoholName: 'Amber Ale',
        pairingDescription: 'A snack favorite with a malty amber ale.',
        keyIngredients: ['Soft Pretzels', 'Cheese Dip'],
        flavorProfile: 'Malty and Salty',
        vegan: false,
        glutenFree: false,
      ),
       PairingModel(
        foodName: 'Buffalo Wings',
        alcoholName: 'IPA',
        pairingDescription: 'Kick up the heat with spicy wings and a hoppy IPA.',
        keyIngredients: ['Buffalo Wings', 'IPA'],
        flavorProfile: 'Spicy',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Cajun Shrimp Boil',
        alcoholName: 'Beer',
        pairingDescription: 'Enjoy the spice of Cajun shrimp boil with a cold beer.',
        keyIngredients: ['Shrimp', 'Corn', 'Potatoes', 'Andouille sausage'],
        flavorProfile: 'Spicy and flavorful',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Buffalo Chicken Sliders',
        alcoholName: 'Beer',
        pairingDescription: 'Pair the heat of buffalo chicken sliders with the crispness of beer.',
        keyIngredients: ['Chicken breast', 'Buffalo sauce', 'Slider buns', 'Blue cheese'],
        flavorProfile: 'Spicy and savory',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Spicy Thai Curry',
        alcoholName: 'IPA',
        pairingDescription: 'Enhance the spice of Thai curry with the hoppy bitterness of IPA.',
        keyIngredients: ['Chicken', 'Coconut milk', 'Red curry paste', 'Vegetables'],
        flavorProfile: 'Spicy and aromatic',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Jalapeño Popper Pizza',
        alcoholName: 'IPA',
        pairingDescription: 'Kick up the heat with a Jalapeño Popper Pizza paired with an IPA.',
        keyIngredients: ['Pizza dough', 'Cream cheese', 'Jalapeños', 'Bacon'],
        flavorProfile: 'Spicy and cheesy',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Spaghetti Bolognese',
        alcoholName: 'Italian Lager',
        pairingDescription: 'Pair the hearty flavors of Spaghetti Bolognese with a refreshing Italian Lager.',
        keyIngredients: ['Ground beef', 'Tomato sauce', 'Spaghetti pasta', 'Parmesan cheese'],
        flavorProfile: 'Rich and meaty',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Caprese Salad',
        alcoholName: 'Wheat Beer',
        pairingDescription: 'Enhance the freshness of Caprese Salad with a light and citrusy Wheat Beer.',
        keyIngredients: ['Tomatoes', 'Fresh mozzarella', 'Basil', 'Balsamic glaze'],
        flavorProfile: 'Fresh and vibrant',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Pesto Pasta',
        alcoholName: 'Citrus IPA',
        pairingDescription: 'Elevate the herbal notes of Pesto Pasta with the citrusy hops of an IPA.',
        keyIngredients: ['Basil', 'Garlic', 'Pine nuts', 'Parmesan cheese'],
        flavorProfile: 'Herbaceous and citrusy',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Seafood Risotto',
        alcoholName: 'Double IPA',
        pairingDescription: 'Pair the richness of Seafood Risotto with the boldness of a Double IPA.',
        keyIngredients: ['Arborio rice', 'Shrimp', 'Scallops', 'White wine'],
        flavorProfile: 'Rich and hoppy',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Tiramisu',
        alcoholName: 'Imperial IPA',
        pairingDescription: 'Indulge in the decadence of Tiramisu with the robustness of an Imperial IPA.',
        keyIngredients: ['Ladyfingers', 'Espresso', 'Mascarpone cheese', 'Cocoa powder'],
        flavorProfile: 'Rich and intense',
        vegan: false,
        glutenFree: false,
      ),
    ],  // end of beer key (15 pairings)
    'Sake': [
      PairingModel(
        foodName: 'Sushi',
        alcoholName: 'Sake',
        pairingDescription: 'Enhance your sushi experience with a glass of sake.',
        keyIngredients: ['Sushi', 'Sake'],
        flavorProfile: 'Umami',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Tempura',
        alcoholName: 'Sake',
        pairingDescription: 'Crispy tempura paired with a smooth sake.',
        keyIngredients: ['Tempura', 'Sake'],
        flavorProfile: 'Crispy',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Teriyaki Chicken',
        alcoholName: 'Sake',
        pairingDescription: 'Teriyaki chicken and sake, a delightful combination.',
        keyIngredients: ['Teriyaki Chicken', 'Sake'],
        flavorProfile: 'Savory',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Sashimi',
        alcoholName: 'Sake',
        pairingDescription: 'Enjoy the delicate flavors of sashimi with a smooth sake.',
        keyIngredients: ['Fresh fish'],
        flavorProfile: 'Light and clean',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Miso Soup',
        alcoholName: 'Sake',
        pairingDescription: 'Warm up with miso soup and a comforting cup of sake.',
        keyIngredients: ['Miso paste', 'Tofu', 'Seaweed'],
        flavorProfile: 'Umami-rich',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Yakitori (Grilled Chicken Skewers)',
        alcoholName: 'Sake',
        pairingDescription: 'Savor the grilled goodness of yakitori paired with sake.',
        keyIngredients: ['Chicken', 'Soy sauce', 'Green onions'],
        flavorProfile: 'Savory and slightly sweet',
        vegan: false,
        glutenFree: false,
      ),
    ],  // end of sake key (6 pairings)
    'Tequila': [
      PairingModel(
        foodName: 'Tacos',
        alcoholName: 'Tequila',
        pairingDescription: 'Salty, spicy tacos to complement Tequila.',
        keyIngredients: ['Tacos', 'Tequila'],
        flavorProfile: 'Spicy',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Guacamole',
        alcoholName: 'Tequila',
        pairingDescription: 'Pair the freshness of guacamole with a smooth tequila.',
        keyIngredients: ['Avocado', 'Tomato', 'Lime'],
        flavorProfile: 'Creamy and tangy',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Ceviche',
        alcoholName: 'Tequila',
        pairingDescription: 'Enhance the flavors of ceviche with a citrusy tequila.',
        keyIngredients: ['White fish', 'Lime', 'Cilantro'],
        flavorProfile: 'Bright and zesty',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Chiles Rellenos',
        alcoholName: 'Tequila',
        pairingDescription: 'Spice up your meal with chiles rellenos and a shot of tequila.',
        keyIngredients: ['Poblano peppers', 'Cheese', 'Tomato sauce'],
        flavorProfile: 'Spicy and savory',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Shrimp Tacos',
        alcoholName: 'Tequila',
        pairingDescription: 'Enjoy the flavors of shrimp tacos with a tequila twist.',
        keyIngredients: ['Shrimp', 'Cabbage slaw', 'Chipotle mayo'],
        flavorProfile: 'Savory and smoky',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Mango Salsa',
        alcoholName: 'Tequila',
        pairingDescription: 'Dip into the tropical goodness of mango salsa with tequila.',
        keyIngredients: ['Mango', 'Red onion', 'Cilantro'],
        flavorProfile: 'Sweet and refreshing',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Tamales',
        alcoholName: 'Tequila',
        pairingDescription: 'Savor the comfort of tamales with a tequila accompaniment.',
        keyIngredients: ['Corn masa', 'Meat filling', 'Chiles'],
        flavorProfile: 'Hearty and satisfying',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Chicken Mole',
        alcoholName: 'Tequila',
        pairingDescription: 'Experience the rich flavors of chicken mole with tequila.',
        keyIngredients: ['Chicken', 'Chocolate sauce', 'Chiles'],
        flavorProfile: 'Complex and indulgent',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Pineapple Salsa',
        alcoholName: 'Tequila',
        pairingDescription: 'Indulge in the tropical delight of pineapple salsa with tequila.',
        keyIngredients: ['Pineapple', 'Red pepper', 'Cilantro'],
        flavorProfile: 'Sweet and tangy',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Quesadillas',
        alcoholName: 'Tequila',
        pairingDescription: 'Pair tequila with cheesy quesadillas for a delightful treat.',
        keyIngredients: ['Tortillas', 'Cheese', 'Salsa'],
        flavorProfile: 'Cheesy and satisfying',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Steak Fajitas',
        alcoholName: 'Tequila',
        pairingDescription: 'Sizzle up your meal with steak fajitas and a tequila kick.',
        keyIngredients: ['Steak', 'Bell peppers', 'Onions'],
        flavorProfile: 'Smoky and flavorful',
        vegan: false,
        glutenFree: true,
      ),
    ],  // end of tequila key (11 pairings)
    'Whiskey': [
      PairingModel(
        foodName: 'Smoked Salmon',
        alcoholName: 'Whiskey',
        pairingDescription: 'Elevate the richness of smoked salmon with a fine whiskey.',
        keyIngredients: ['Salmon', 'Dill', 'Lemon'],
        flavorProfile: 'Smoky and savory',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Blue Cheese',
        alcoholName: 'Whiskey',
        pairingDescription: 'Experience the bold flavors of blue cheese with a smooth whiskey.',
        keyIngredients: ['Blue cheese', 'Crackers', 'Honey'],
        flavorProfile: 'Creamy and pungent',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'BBQ Ribs',
        alcoholName: 'Whiskey',
        pairingDescription: 'Savor the smoky goodness of BBQ ribs with a whiskey accompaniment.',
        keyIngredients: ['Pork ribs', 'BBQ sauce', 'Coleslaw'],
        flavorProfile: 'Sweet and savory',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Dark Chocolate',
        alcoholName: 'Whiskey',
        pairingDescription: 'Indulge in the decadence of dark chocolate with a whiskey twist.',
        keyIngredients: ['Dark chocolate', 'Nuts', 'Berries'],
        flavorProfile: 'Rich and bittersweet',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Grilled Steak',
        alcoholName: 'Whiskey',
        pairingDescription: 'Pair a hearty grilled steak with the robust flavors of whiskey.',
        keyIngredients: ['Steak', 'Rosemary', 'Garlic'],
        flavorProfile: 'Hearty and smoky',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Apple Pie',
        alcoholName: 'Whiskey',
        pairingDescription: 'Complement the sweetness of apple pie with a hint of whiskey.',
        keyIngredients: ['Apples', 'Cinnamon', 'Pie crust'],
        flavorProfile: 'Warm and comforting',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Pulled Pork Sandwich',
        alcoholName: 'Whiskey',
        pairingDescription: 'Enjoy the bold flavors of pulled pork sandwiched between buns with whiskey.',
        keyIngredients: ['Pulled pork', 'BBQ sauce', 'Pickles'],
        flavorProfile: 'Savory and tangy',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Caramel Popcorn',
        alcoholName: 'Whiskey',
        pairingDescription: 'Pair the sweet crunchiness of caramel popcorn with a sip of whiskey.',
        keyIngredients: ['Popcorn', 'Caramel', 'Sea salt'],
        flavorProfile: 'Sweet and salty',
        vegan: true,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Ginger Chicken Stir Fry',
        alcoholName: 'Whiskey',
        pairingDescription: 'Savor the Asian-inspired flavors of ginger chicken stir fry with whiskey.',
        keyIngredients: ['Chicken', 'Ginger', 'Vegetables'],
        flavorProfile: 'Spicy and aromatic',
        vegan: false,
        glutenFree: false,
      ),
      PairingModel(
        foodName: 'Brie Cheese',
        alcoholName: 'Whiskey',
        pairingDescription: 'Experience the creamy goodness of brie cheese with a side of whiskey.',
        keyIngredients: ['Brie cheese', 'Baguette', 'Grapes'],
        flavorProfile: 'Buttery and mild',
        vegan: false,
        glutenFree: false,
      ),
    ],  // end of whiskey key (10 pairings)
    'Gin': [
      PairingModel(
        foodName: 'Ceviche',
        alcoholName: 'Gin and Tonic',
        pairingDescription: 'Pair the freshness of Ceviche with a classic Gin and Tonic.',
        keyIngredients: ['White fish', 'Shrimp', 'Lime juice', 'Cilantro'],
        flavorProfile: 'Citrusy and crisp',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Smoked Salmon Canapés',
        alcoholName: 'Martini',
        pairingDescription: 'Elevate the elegance of Smoked Salmon Canapés with a classic Martini.',
        keyIngredients: ['Smoked salmon', 'Cream cheese', 'Dill', 'Crostini'],
        flavorProfile: 'Savory and sophisticated',
        vegan: false,
        glutenFree: false,
      ),
     PairingModel(
        foodName: 'Lemon Herb Grilled Chicken',
        alcoholName: 'Gin and Tonic',
        pairingDescription: 'Pair the herbaceous flavors of grilled chicken with a zesty Gin and Tonic.',
        keyIngredients: ['Chicken breasts', 'Lemon', 'Herbs', 'Gin', 'Tonic water'],
        flavorProfile: 'Herbaceous and refreshing',
        vegan: false,
        glutenFree: true,
      ),
      PairingModel(
        foodName: 'Cucumber Avocado Salad',
        alcoholName: 'Cucumber Gin Cooler',
        pairingDescription: 'Refresh your palate with a Cucumber Avocado Salad and a cooling Cucumber Gin Cooler.',
        keyIngredients: ['Cucumber', 'Avocado', 'Mint', 'Gin', 'Simple syrup'],
        flavorProfile: 'Crisp and cooling',
        vegan: true,
        glutenFree: true,
      ),
    ],  // end of gin key (4 pairings)
  }; // end of map (_allPairings) for hardcoded data

  Map<String, List<PairingModel>> getAllPairings() {
    return _allPairings;
  }
}